name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Mr. Mritunjay"
      - name: Print Goodbye
        run: echo "Mritunjay It's done bro..."
